name: Build Node.js project
on:
  push:
    branches:
      - "**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: deploy railway
        uses: bervProject/railway-deploy@main
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
        with:
          service: "tp5Lenny"

      - name: deploy vercel
        working-directory: frontend
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_AUTH_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG}}
          vercel-project-id: ${{ secrets.VERCEL_SITE_ID}}